#!/usr/bin/env python3
"""Generate ONE identical Rust Finalizer test from the independently checked,
content-hashed four-distinct-ID causal-DAG packet. No model verdict is asserted.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

SOURCE_SHA = "2d2c3d879b1a078693c8551385efb54a811d7172"
SCHEMA = "aria-cbc-distinct-id-rust-replay-input/v1"
TEST_NAME = "aria_exact_source_dag_finalizer_observation"


def canonical(value):
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")


def digest(blob):
    return hashlib.sha256(blob).hexdigest()


def check(packet):
    body = {k: v for k, v in packet.items() if k != "packetSha256"}
    if digest(canonical(body)) != packet.get("packetSha256"):
        raise ValueError("Packet integrity mismatch")
    if packet.get("schema") != SCHEMA or packet.get("sourceCommit") != SOURCE_SHA:
        raise ValueError("Unsupported source packet")
    if packet.get("selection") != "MODEL_CANDIDATE_READY_FOR_INDEPENDENT_RUST_REPLAY":
        raise ValueError("No independently replayable source-model candidate")
    if packet.get("rustReplayVerified") is not False or packet.get("wireIngressVerified") is not False:
        raise ValueError("Source-model claims were silently elevated")
    graph = packet["sourceGraph"]
    if digest(canonical(graph)) != packet["exactGraphSha256"]:
        raise ValueError("Source DAG integrity mismatch")
    if graph["justifications"] != packet["selectedJustificationIds"]:
        raise ValueError("Selected IDs do not match the source DAG")
    if len(graph["justifications"]) != 4 or len(set(graph["justifications"])) != 4:
        raise ValueError("Four distinct IDs required")
    messages = graph["messages"]
    ids = {x["id"] for x in messages}
    if len(ids) != len(messages):
        raise ValueError("Source DAG contains duplicate message IDs")
    if any(parent not in ids for msg in messages for parent in msg["parents"]):
        raise ValueError("Missing source DAG parent")
    if any(msg["id"] not in ids for msg in messages):
        raise ValueError("Invalid source graph message")
    return graph


def rust_string(value):
    if not isinstance(value, str) or not re.fullmatch(r"[a-zA-Z0-9_-]{1,80}", value):
        raise ValueError("Unexpected message identity or sender label")
    return json.dumps(value)


def rust_list(values):
    return "&[" + ", ".join(rust_string(value) for value in values) + "]"


def emit(packet):
    graph = check(packet)
    source_messages = []
    for m in graph["messages"]:
        if not isinstance(m["senderSeq"], int) or not (0 <= m["senderSeq"] < 1000000):
            raise ValueError("Invalid source message sequence")
        source_messages.append(
            "        msg(" + rust_string(m["id"]) + ", " + rust_string(m["sender"]) +
            ", " + str(m["senderSeq"]) + ", " + rust_list(m["parents"]) +
            ", " + rust_list(m["seen"]) + "),"
        )
    bonds = []
    for sender, stake in sorted(graph["bondsMap"].items()):
        if not isinstance(stake, int) or not (0 <= stake < 100000000):
            raise ValueError("Invalid source stake")
        bonds.append("        (" + rust_string(sender) + ".to_string(), " + str(stake) + "i64),")
    ids = rust_list(graph["justifications"])
    graph_sha = packet["exactGraphSha256"]
    packet_sha = packet["packetSha256"]
    return """// AUTOGENERATED from immutable source-model causal graph; test-only, not an upstream fix.
// Never claim that a Rust Finalizer result proves block ingress or deployed finality.
use std::collections::{BTreeMap, BTreeSet};
use rchain_block_storage::dag::finalizer::{Finalizer, Message};
use rchain_shared::refined::{BlockHeight, NonNegI64, SeqNum};

fn msg(id: &str, sender: &str, seq: i64, parents: &[&str], seen: &[&str])
    -> Message<String, String> {
    Message {
        id: id.to_string(), height: BlockHeight::zero(), sender: sender.to_string(),
        sender_seq: SeqNum::try_from(seq).unwrap(), bonds_map: BTreeMap::new(),
        parents: parents.iter().map(|x| x.to_string()).collect(),
        fringe: BTreeSet::new(),
        seen: seen.iter().map(|x| x.to_string()).collect(),
    }
}
fn oldest_same_sender(message: &Message<String, String>,
    all: &BTreeMap<String, Message<String, String>>)
    -> Message<String, String> {
    let mut current = message.clone();
    for _ in 0..1000 {
        let mut same: Vec<_> = current.parents.iter()
            .filter_map(|id| all.get(id))
            .filter(|m| m.sender == current.sender)
            .cloned().collect();
        match same.pop() {
            Some(next) => current = next,
            None => return current,
        }
    }
    panic!("Unexpected self-parent loop");
}
#[test]
fn aria_exact_source_dag_finalizer_observation() {
    let graph_sha = "GRAPH_SHA";
    let packet_sha = "PACKET_SHA";
    let messages = vec![
SOURCE_MESSAGES
    ];
    let source_message_count = messages.len();
    let all: BTreeMap<String, Message<String, String>> =
        messages.into_iter().map(|m| (m.id.clone(), m)).collect();
    assert_eq!(source_message_count, all.len(), "No duplicate message IDs allowed");
    let ids: BTreeSet<String> = (SOURCE_JUSTIFICATIONS).iter().map(|id| id.to_string()).collect();
    assert_eq!(ids.len(), 4, "The same four source IDs must reach the Rust Finalizer");
    let justifications: BTreeSet<Message<String, String>> =
        ids.iter().map(|id| all.get(id).expect("selected source ID exists").clone()).collect();
    assert_eq!(justifications.len(), 4);
    let bonds: BTreeMap<String, NonNegI64> = [
SOURCE_BONDS
    ].into_iter().map(|(s, stake)| (s, NonNegI64::try_from(stake).unwrap())).collect();
    let finalizer = Finalizer::new(&all);
    let minimum: Vec<_> = justifications.iter()
        .map(|m| oldest_same_sender(m, &all)).collect();
    let minimum_ids: Vec<_> = minimum.iter().map(|m| m.id.as_str()).collect();
    let distinct_minimum_senders: BTreeSet<_> = minimum.iter().map(|m| m.sender.as_str()).collect();
    let gate = finalizer.check_min_messages(&minimum, &bonds);
    let next_layer = finalizer.calculate_next_layer(&minimum);
    // Initial iteration only; all message fringes are empty in this model packet.
    // The minimum chain is a test projection; support/fringe call production methods.
    let support = finalizer.calculate_next_fringe_support_map(
        &justifications, &next_layer, &BTreeSet::new());
    let next_ids: BTreeMap<_, _> = next_layer.iter()
        .map(|(s, m)| (s.clone(), m.id.clone())).collect();
    let support_json: BTreeMap<_, BTreeMap<_, Vec<_>>> = support.iter()
        .map(|(s, inner)| (s.clone(), inner.iter()
            .map(|(n, observers)| (n.clone(), observers.iter().cloned().collect()))
            .collect())).collect();
    let bonded: BTreeSet<_> = bonds.keys().cloned().collect();
    let supporting_stake: i128 = support.iter()
        .filter(|(_, inner)| !inner.is_empty() && inner.values().all(|v| v == &bonded))
        .filter_map(|(sender, _)| bonds.get(sender))
        .map(|stake| i128::from(i64::from(*stake))).sum();
    let total_stake: i128 = bonds.values().map(|v| i128::from(i64::from(*v))).sum();
    let initial_fringe_predicate = finalizer.calculate_fringe(&support, &bonds);
    let (_parent_fringe, new_fringe) = finalizer.calculate_finalization(&justifications, &bonds);
    let new_fringe_ids: Vec<_> = new_fringe
        .as_ref().map(|s| s.iter().map(|m| m.id.as_str()).collect()).unwrap_or_default();
    println!(
        "ARIA_EXACT_DAG_V1|graph_sha256={}|packet_sha256={}|source_message_count={}|unique_justifications={}|minimum_message_ids={}|minimum_unique_senders={}|count_gate={}|next_layer_senders={}|new_fringe={}|new_fringe_ids={}|next_layer_ids={:?}|support_map={:?}|supporting_stake={}|total_stake={}|initial_fringe_predicate={}",
        graph_sha, packet_sha, all.len(), justifications.len(),
        minimum_ids.join(","), distinct_minimum_senders.len(), gate,
        next_layer.len(), new_fringe.is_some(), new_fringe_ids.join(","),
        next_ids, support_json, supporting_stake, total_stake, initial_fringe_predicate,
    );
}
""".replace("GRAPH_SHA", graph_sha).replace("PACKET_SHA", packet_sha).replace(
        "SOURCE_MESSAGES", "\n".join(source_messages)).replace(
        "SOURCE_JUSTIFICATIONS", ids).replace(
        "SOURCE_BONDS", "\n".join(bonds))


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--packet", required=True)
    p.add_argument("--output", required=True)
    a = p.parse_args()
    try:
        packet = json.loads(Path(a.packet).read_text(encoding="utf8"))
        source = emit(packet)
        out = Path(a.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(source, encoding="utf8")
        print(json.dumps({
            "generated_source_sha256": digest(source.encode()),
            "sourceGraphSha256": packet["exactGraphSha256"],
            "inputPacketSha256": packet["packetSha256"],
            "selectedFourUniqueMessageIds": packet["selectedJustificationIds"],
            "rustTestSourceEmitted": True,
            "rustTestExecuted": False,
        }))
        return 0
    except (OSError, KeyError, ValueError, TypeError, json.JSONDecodeError) as e:
        print("Exact Rust source generator rejected packet: " + str(e), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
