/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as CausalityRouteImport } from './routes/causality'
import { Route as CounterfactualRouteImport } from './routes/counterfactual'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as ReplayRouteImport } from './routes/replay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const CausalityRoute = CausalityRouteImport.update({
  id: '/causality',
  path: '/causality',
  getParentRoute: () => rootRouteImport,
} as any)
const CounterfactualRoute = CounterfactualRouteImport.update({
  id: '/counterfactual',
  path: '/counterfactual',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/causality': typeof CausalityRoute
  '/counterfactual': typeof CounterfactualRoute
  '/evidence': typeof EvidenceRoute
  '/replay': typeof ReplayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/causality': typeof CausalityRoute
  '/counterfactual': typeof CounterfactualRoute
  '/evidence': typeof EvidenceRoute
  '/replay': typeof ReplayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/causality': typeof CausalityRoute
  '/counterfactual': typeof CounterfactualRoute
  '/evidence': typeof EvidenceRoute
  '/replay': typeof ReplayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/causality'
    | '/counterfactual'
    | '/evidence'
    | '/replay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/causality'
    | '/counterfactual'
    | '/evidence'
    | '/replay'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/causality'
    | '/counterfactual'
    | '/evidence'
    | '/replay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  CausalityRoute: typeof CausalityRoute
  CounterfactualRoute: typeof CounterfactualRoute
  EvidenceRoute: typeof EvidenceRoute
  ReplayRoute: typeof ReplayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causality': {
      id: '/causality'
      path: '/causality'
      fullPath: '/causality'
      preLoaderRoute: typeof CausalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counterfactual': {
      id: '/counterfactual'
      path: '/counterfactual'
      fullPath: '/counterfactual'
      preLoaderRoute: typeof CounterfactualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  CausalityRoute: CausalityRoute,
  CounterfactualRoute: CounterfactualRoute,
  EvidenceRoute: EvidenceRoute,
  ReplayRoute: ReplayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
